# Generated by Django 5.1.2 on 2024-10-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_empanada_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Empanada',
        ),
    ]
