# Generated by Django 4.2.4 on 2024-11-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
