# Generated by Django 4.2.4 on 2024-11-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='avatar',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
